//
// Measure.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Measure: Codable, JSONEncodable, Hashable {

    /** The measurement in imperial units */
    public var imperial: String?
    /** The measurement in metric units */
    public var metric: String?

    public init(imperial: String? = nil, metric: String? = nil) {
        self.imperial = imperial
        self.metric = metric
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case imperial
        case metric
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(imperial, forKey: .imperial)
        try container.encodeIfPresent(metric, forKey: .metric)
    }
}

